version: '3.2'

services:


  web:
    container_name: web
    build: .
    volumes:
      - ./:/app
    command: gunicorn main:app -b :8888 --worker-class aiohttp.GunicornWebWorker --reload --access-logfile -
    ports:
      - "8888:8888"