version: '3.2'

services:


  web:
    container_name: web
    build: .
    command: gunicorn main:app -b :8888 --worker-class aiohttp.GunicornWebWorker --reload --access-logfile -
    ports:
      - "8888:8888"
    depends_on:
      - redis


  redis:
    container_name: redis
    image: redis:latest
    restart: unless-stopped
    ports:
      - "6379:6379"